language: java

jdk:
  - openjdk11

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false --settings settings.xml
  - mvn clean install sonar:sonar -Dsonar.projectKey=BenSlabbert_trak -Dsonar.organization=benslabbert-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN --settings settings.xml
  - mvn clean deploy --settings settings.xml
