language: java

jdk:
  - openjdk11

script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=BenSlabbert_trak -Dsonar.organization=benslabbert-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
