// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/search/search_api.proto

package com.trak.grpc.search.v1;

public interface CategorySearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.search.v1.CategorySearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string search = 1;</code>
   */
  java.lang.String getSearch();
  /**
   * <code>string search = 1;</code>
   */
  com.google.protobuf.ByteString
      getSearchBytes();
}
