/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.io.github.benslabbert.trak.grpc.HelloRequest', null, global);
goog.exportSymbol('proto.io.github.benslabbert.trak.grpc.HelloResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.github.benslabbert.trak.grpc.HelloRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    proto.io.github.benslabbert.trak.grpc.HelloRequest.displayName = 'proto.io.github.benslabbert.trak.grpc.HelloRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto suitable for use in Soy templates.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
     * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
     *     for transitional soy proto support: http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.io.github.benslabbert.trak.grpc.HelloRequest.prototype.toObject = function(opt_includeInstance) {
        return proto.io.github.benslabbert.trak.grpc.HelloRequest.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Whether to include the JSPB
     *     instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.io.github.benslabbert.trak.grpc.HelloRequest} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.io.github.benslabbert.trak.grpc.HelloRequest.toObject = function(includeInstance, msg) {
        var f, obj = {
            firstName: jspb.Message.getFieldWithDefault(msg, 1, ""),
            lastName: jspb.Message.getFieldWithDefault(msg, 2, "")
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.github.benslabbert.trak.grpc.HelloRequest}
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.io.github.benslabbert.trak.grpc.HelloRequest;
    return proto.io.github.benslabbert.trak.grpc.HelloRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.github.benslabbert.trak.grpc.HelloRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.github.benslabbert.trak.grpc.HelloRequest}
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setFirstName(value);
                break;
            case 2:
                var value = /** @type {string} */ (reader.readString());
                msg.setLastName(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.io.github.benslabbert.trak.grpc.HelloRequest.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.github.benslabbert.trak.grpc.HelloRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getFirstName();
    if (f.length > 0) {
        writer.writeString(
            1,
            f
        );
    }
    f = message.getLastName();
    if (f.length > 0) {
        writer.writeString(
            2,
            f
        );
    }
};


/**
 * optional string first_name = 1;
 * @return {string}
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest.prototype.getFirstName = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.github.benslabbert.trak.grpc.HelloRequest.prototype.setFirstName = function(value) {
    jspb.Message.setField(this, 1, value);
};


/**
 * optional string last_name = 2;
 * @return {string}
 */
proto.io.github.benslabbert.trak.grpc.HelloRequest.prototype.getLastName = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.io.github.benslabbert.trak.grpc.HelloRequest.prototype.setLastName = function(value) {
    jspb.Message.setField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.io.github.benslabbert.trak.grpc.HelloResponse = function(opt_data) {
    jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.io.github.benslabbert.trak.grpc.HelloResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
    proto.io.github.benslabbert.trak.grpc.HelloResponse.displayName = 'proto.io.github.benslabbert.trak.grpc.HelloResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
    /**
     * Creates an object representation of this proto suitable for use in Soy templates.
     * Field names that are reserved in JavaScript and will be renamed to pb_name.
     * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
     * For the list of reserved names please see:
     *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
     * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
     *     for transitional soy proto support: http://goto/soy-param-migration
     * @return {!Object}
     */
    proto.io.github.benslabbert.trak.grpc.HelloResponse.prototype.toObject = function(opt_includeInstance) {
        return proto.io.github.benslabbert.trak.grpc.HelloResponse.toObject(opt_includeInstance, this);
    };


    /**
     * Static version of the {@see toObject} method.
     * @param {boolean|undefined} includeInstance Whether to include the JSPB
     *     instance for transitional soy proto support:
     *     http://goto/soy-param-migration
     * @param {!proto.io.github.benslabbert.trak.grpc.HelloResponse} msg The msg instance to transform.
     * @return {!Object}
     * @suppress {unusedLocalVariables} f is only used for nested messages
     */
    proto.io.github.benslabbert.trak.grpc.HelloResponse.toObject = function(includeInstance, msg) {
        var f, obj = {
            greeting: jspb.Message.getFieldWithDefault(msg, 1, "")
        };

        if (includeInstance) {
            obj.$jspbMessageInstance = msg;
        }
        return obj;
    };
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.io.github.benslabbert.trak.grpc.HelloResponse}
 */
proto.io.github.benslabbert.trak.grpc.HelloResponse.deserializeBinary = function(bytes) {
    var reader = new jspb.BinaryReader(bytes);
    var msg = new proto.io.github.benslabbert.trak.grpc.HelloResponse;
    return proto.io.github.benslabbert.trak.grpc.HelloResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.io.github.benslabbert.trak.grpc.HelloResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.io.github.benslabbert.trak.grpc.HelloResponse}
 */
proto.io.github.benslabbert.trak.grpc.HelloResponse.deserializeBinaryFromReader = function(msg, reader) {
    while (reader.nextField()) {
        if (reader.isEndGroup()) {
            break;
        }
        var field = reader.getFieldNumber();
        switch (field) {
            case 1:
                var value = /** @type {string} */ (reader.readString());
                msg.setGreeting(value);
                break;
            default:
                reader.skipField();
                break;
        }
    }
    return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.io.github.benslabbert.trak.grpc.HelloResponse.prototype.serializeBinary = function() {
    var writer = new jspb.BinaryWriter();
    proto.io.github.benslabbert.trak.grpc.HelloResponse.serializeBinaryToWriter(this, writer);
    return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.io.github.benslabbert.trak.grpc.HelloResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.io.github.benslabbert.trak.grpc.HelloResponse.serializeBinaryToWriter = function(message, writer) {
    var f = undefined;
    f = message.getGreeting();
    if (f.length > 0) {
        writer.writeString(
            1,
            f
        );
    }
};


/**
 * optional string greeting = 1;
 * @return {string}
 */
proto.io.github.benslabbert.trak.grpc.HelloResponse.prototype.getGreeting = function() {
    return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.io.github.benslabbert.trak.grpc.HelloResponse.prototype.setGreeting = function(value) {
    jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.io.github.benslabbert.trak.grpc);
