// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface AddProductRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.AddProductRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();
}
