// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface CategoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.CategoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 category_id = 1;</code>
   */
  int getCategoryId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .trak.grpc.gateway.v1.ProductMessage products = 3;</code>
   */
  java.util.List<com.trak.grpc.gateway.v1.ProductMessage> 
      getProductsList();
  /**
   * <code>repeated .trak.grpc.gateway.v1.ProductMessage products = 3;</code>
   */
  com.trak.grpc.gateway.v1.ProductMessage getProducts(int index);
  /**
   * <code>repeated .trak.grpc.gateway.v1.ProductMessage products = 3;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .trak.grpc.gateway.v1.ProductMessage products = 3;</code>
   */
  java.util.List<? extends com.trak.grpc.gateway.v1.ProductMessageOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .trak.grpc.gateway.v1.ProductMessage products = 3;</code>
   */
  com.trak.grpc.gateway.v1.ProductMessageOrBuilder getProductsOrBuilder(
      int index);
}
