// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface ChartMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.ChartMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string labels = 1;</code>
   */
  java.util.List<java.lang.String>
      getLabelsList();
  /**
   * <code>repeated string labels = 1;</code>
   */
  int getLabelsCount();
  /**
   * <code>repeated string labels = 1;</code>
   */
  java.lang.String getLabels(int index);
  /**
   * <code>repeated string labels = 1;</code>
   */
  com.google.protobuf.ByteString
      getLabelsBytes(int index);

  /**
   * <code>repeated .trak.grpc.gateway.v1.ChartContentMessage content = 2;</code>
   */
  java.util.List<com.trak.grpc.gateway.v1.ChartContentMessage> 
      getContentList();
  /**
   * <code>repeated .trak.grpc.gateway.v1.ChartContentMessage content = 2;</code>
   */
  com.trak.grpc.gateway.v1.ChartContentMessage getContent(int index);
  /**
   * <code>repeated .trak.grpc.gateway.v1.ChartContentMessage content = 2;</code>
   */
  int getContentCount();
  /**
   * <code>repeated .trak.grpc.gateway.v1.ChartContentMessage content = 2;</code>
   */
  java.util.List<? extends com.trak.grpc.gateway.v1.ChartContentMessageOrBuilder> 
      getContentOrBuilderList();
  /**
   * <code>repeated .trak.grpc.gateway.v1.ChartContentMessage content = 2;</code>
   */
  com.trak.grpc.gateway.v1.ChartContentMessageOrBuilder getContentOrBuilder(
      int index);
}
