// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.Empty)
    com.google.protobuf.MessageOrBuilder {
}
