// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface GetAllPromotionsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.GetAllPromotionsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .trak.grpc.gateway.v1.PromotionMessage promotions = 1;</code>
   */
  java.util.List<com.trak.grpc.gateway.v1.PromotionMessage> 
      getPromotionsList();
  /**
   * <code>repeated .trak.grpc.gateway.v1.PromotionMessage promotions = 1;</code>
   */
  com.trak.grpc.gateway.v1.PromotionMessage getPromotions(int index);
  /**
   * <code>repeated .trak.grpc.gateway.v1.PromotionMessage promotions = 1;</code>
   */
  int getPromotionsCount();
  /**
   * <code>repeated .trak.grpc.gateway.v1.PromotionMessage promotions = 1;</code>
   */
  java.util.List<? extends com.trak.grpc.gateway.v1.PromotionMessageOrBuilder> 
      getPromotionsOrBuilderList();
  /**
   * <code>repeated .trak.grpc.gateway.v1.PromotionMessage promotions = 1;</code>
   */
  com.trak.grpc.gateway.v1.PromotionMessageOrBuilder getPromotionsOrBuilder(
      int index);

  /**
   * <code>.trak.grpc.gateway.v1.PageResponse page_response = 2;</code>
   */
  boolean hasPageResponse();
  /**
   * <code>.trak.grpc.gateway.v1.PageResponse page_response = 2;</code>
   */
  com.trak.grpc.gateway.v1.PageResponse getPageResponse();
  /**
   * <code>.trak.grpc.gateway.v1.PageResponse page_response = 2;</code>
   */
  com.trak.grpc.gateway.v1.PageResponseOrBuilder getPageResponseOrBuilder();
}
