// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

/**
 * <pre>
 * Details of the requested page.
 * </pre>
 *
 * Protobuf type {@code trak.grpc.gateway.v1.PageResponse}
 */
public  final class PageResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trak.grpc.gateway.v1.PageResponse)
    PageResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PageResponse.newBuilder() to construct.
  private PageResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PageResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PageResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PageResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            currentPageNumber_ = input.readUInt32();
            break;
          }
          case 16: {

            lastPageNumber_ = input.readUInt32();
            break;
          }
          case 24: {

            totalItems_ = input.readUInt32();
            break;
          }
          case 32: {

            pageSize_ = input.readUInt32();
            break;
          }
          case 40: {

            isLastPage_ = input.readBool();
            break;
          }
          case 48: {

            isFirstPage_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_PageResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_PageResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trak.grpc.gateway.v1.PageResponse.class, com.trak.grpc.gateway.v1.PageResponse.Builder.class);
  }

  public static final int CURRENT_PAGE_NUMBER_FIELD_NUMBER = 1;
  private int currentPageNumber_;
  /**
   * <code>uint32 current_page_number = 1;</code>
   */
  public int getCurrentPageNumber() {
    return currentPageNumber_;
  }

  public static final int LAST_PAGE_NUMBER_FIELD_NUMBER = 2;
  private int lastPageNumber_;
  /**
   * <code>uint32 last_page_number = 2;</code>
   */
  public int getLastPageNumber() {
    return lastPageNumber_;
  }

  public static final int TOTAL_ITEMS_FIELD_NUMBER = 3;
  private int totalItems_;
  /**
   * <code>uint32 total_items = 3;</code>
   */
  public int getTotalItems() {
    return totalItems_;
  }

  public static final int PAGE_SIZE_FIELD_NUMBER = 4;
  private int pageSize_;
  /**
   * <code>uint32 page_size = 4;</code>
   */
  public int getPageSize() {
    return pageSize_;
  }

  public static final int IS_LAST_PAGE_FIELD_NUMBER = 5;
  private boolean isLastPage_;
  /**
   * <code>bool is_last_page = 5;</code>
   */
  public boolean getIsLastPage() {
    return isLastPage_;
  }

  public static final int IS_FIRST_PAGE_FIELD_NUMBER = 6;
  private boolean isFirstPage_;
  /**
   * <code>bool is_first_page = 6;</code>
   */
  public boolean getIsFirstPage() {
    return isFirstPage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (currentPageNumber_ != 0) {
      output.writeUInt32(1, currentPageNumber_);
    }
    if (lastPageNumber_ != 0) {
      output.writeUInt32(2, lastPageNumber_);
    }
    if (totalItems_ != 0) {
      output.writeUInt32(3, totalItems_);
    }
    if (pageSize_ != 0) {
      output.writeUInt32(4, pageSize_);
    }
    if (isLastPage_ != false) {
      output.writeBool(5, isLastPage_);
    }
    if (isFirstPage_ != false) {
      output.writeBool(6, isFirstPage_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (currentPageNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, currentPageNumber_);
    }
    if (lastPageNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, lastPageNumber_);
    }
    if (totalItems_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(3, totalItems_);
    }
    if (pageSize_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, pageSize_);
    }
    if (isLastPage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, isLastPage_);
    }
    if (isFirstPage_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(6, isFirstPage_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trak.grpc.gateway.v1.PageResponse)) {
      return super.equals(obj);
    }
    com.trak.grpc.gateway.v1.PageResponse other = (com.trak.grpc.gateway.v1.PageResponse) obj;

    if (getCurrentPageNumber()
        != other.getCurrentPageNumber()) return false;
    if (getLastPageNumber()
        != other.getLastPageNumber()) return false;
    if (getTotalItems()
        != other.getTotalItems()) return false;
    if (getPageSize()
        != other.getPageSize()) return false;
    if (getIsLastPage()
        != other.getIsLastPage()) return false;
    if (getIsFirstPage()
        != other.getIsFirstPage()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CURRENT_PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentPageNumber();
    hash = (37 * hash) + LAST_PAGE_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getLastPageNumber();
    hash = (37 * hash) + TOTAL_ITEMS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalItems();
    hash = (37 * hash) + PAGE_SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getPageSize();
    hash = (37 * hash) + IS_LAST_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsLastPage());
    hash = (37 * hash) + IS_FIRST_PAGE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getIsFirstPage());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.PageResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trak.grpc.gateway.v1.PageResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Details of the requested page.
   * </pre>
   *
   * Protobuf type {@code trak.grpc.gateway.v1.PageResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trak.grpc.gateway.v1.PageResponse)
      com.trak.grpc.gateway.v1.PageResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_PageResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_PageResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trak.grpc.gateway.v1.PageResponse.class, com.trak.grpc.gateway.v1.PageResponse.Builder.class);
    }

    // Construct using com.trak.grpc.gateway.v1.PageResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      currentPageNumber_ = 0;

      lastPageNumber_ = 0;

      totalItems_ = 0;

      pageSize_ = 0;

      isLastPage_ = false;

      isFirstPage_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_PageResponse_descriptor;
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.PageResponse getDefaultInstanceForType() {
      return com.trak.grpc.gateway.v1.PageResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.PageResponse build() {
      com.trak.grpc.gateway.v1.PageResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.PageResponse buildPartial() {
      com.trak.grpc.gateway.v1.PageResponse result = new com.trak.grpc.gateway.v1.PageResponse(this);
      result.currentPageNumber_ = currentPageNumber_;
      result.lastPageNumber_ = lastPageNumber_;
      result.totalItems_ = totalItems_;
      result.pageSize_ = pageSize_;
      result.isLastPage_ = isLastPage_;
      result.isFirstPage_ = isFirstPage_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trak.grpc.gateway.v1.PageResponse) {
        return mergeFrom((com.trak.grpc.gateway.v1.PageResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trak.grpc.gateway.v1.PageResponse other) {
      if (other == com.trak.grpc.gateway.v1.PageResponse.getDefaultInstance()) return this;
      if (other.getCurrentPageNumber() != 0) {
        setCurrentPageNumber(other.getCurrentPageNumber());
      }
      if (other.getLastPageNumber() != 0) {
        setLastPageNumber(other.getLastPageNumber());
      }
      if (other.getTotalItems() != 0) {
        setTotalItems(other.getTotalItems());
      }
      if (other.getPageSize() != 0) {
        setPageSize(other.getPageSize());
      }
      if (other.getIsLastPage() != false) {
        setIsLastPage(other.getIsLastPage());
      }
      if (other.getIsFirstPage() != false) {
        setIsFirstPage(other.getIsFirstPage());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.trak.grpc.gateway.v1.PageResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.trak.grpc.gateway.v1.PageResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int currentPageNumber_ ;
    /**
     * <code>uint32 current_page_number = 1;</code>
     */
    public int getCurrentPageNumber() {
      return currentPageNumber_;
    }
    /**
     * <code>uint32 current_page_number = 1;</code>
     */
    public Builder setCurrentPageNumber(int value) {
      
      currentPageNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 current_page_number = 1;</code>
     */
    public Builder clearCurrentPageNumber() {
      
      currentPageNumber_ = 0;
      onChanged();
      return this;
    }

    private int lastPageNumber_ ;
    /**
     * <code>uint32 last_page_number = 2;</code>
     */
    public int getLastPageNumber() {
      return lastPageNumber_;
    }
    /**
     * <code>uint32 last_page_number = 2;</code>
     */
    public Builder setLastPageNumber(int value) {
      
      lastPageNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 last_page_number = 2;</code>
     */
    public Builder clearLastPageNumber() {
      
      lastPageNumber_ = 0;
      onChanged();
      return this;
    }

    private int totalItems_ ;
    /**
     * <code>uint32 total_items = 3;</code>
     */
    public int getTotalItems() {
      return totalItems_;
    }
    /**
     * <code>uint32 total_items = 3;</code>
     */
    public Builder setTotalItems(int value) {
      
      totalItems_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 total_items = 3;</code>
     */
    public Builder clearTotalItems() {
      
      totalItems_ = 0;
      onChanged();
      return this;
    }

    private int pageSize_ ;
    /**
     * <code>uint32 page_size = 4;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }
    /**
     * <code>uint32 page_size = 4;</code>
     */
    public Builder setPageSize(int value) {
      
      pageSize_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 page_size = 4;</code>
     */
    public Builder clearPageSize() {
      
      pageSize_ = 0;
      onChanged();
      return this;
    }

    private boolean isLastPage_ ;
    /**
     * <code>bool is_last_page = 5;</code>
     */
    public boolean getIsLastPage() {
      return isLastPage_;
    }
    /**
     * <code>bool is_last_page = 5;</code>
     */
    public Builder setIsLastPage(boolean value) {
      
      isLastPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_last_page = 5;</code>
     */
    public Builder clearIsLastPage() {
      
      isLastPage_ = false;
      onChanged();
      return this;
    }

    private boolean isFirstPage_ ;
    /**
     * <code>bool is_first_page = 6;</code>
     */
    public boolean getIsFirstPage() {
      return isFirstPage_;
    }
    /**
     * <code>bool is_first_page = 6;</code>
     */
    public Builder setIsFirstPage(boolean value) {
      
      isFirstPage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bool is_first_page = 6;</code>
     */
    public Builder clearIsFirstPage() {
      
      isFirstPage_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trak.grpc.gateway.v1.PageResponse)
  }

  // @@protoc_insertion_point(class_scope:trak.grpc.gateway.v1.PageResponse)
  private static final com.trak.grpc.gateway.v1.PageResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trak.grpc.gateway.v1.PageResponse();
  }

  public static com.trak.grpc.gateway.v1.PageResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PageResponse>
      PARSER = new com.google.protobuf.AbstractParser<PageResponse>() {
    @java.lang.Override
    public PageResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PageResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PageResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PageResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trak.grpc.gateway.v1.PageResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

