// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface ProductStatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.ProductStatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 min_price = 1;</code>
   */
  int getMinPrice();

  /**
   * <code>uint32 max_price = 2;</code>
   */
  int getMaxPrice();

  /**
   * <code>double mean_price = 3;</code>
   */
  double getMeanPrice();

  /**
   * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
   */
  boolean hasChart();
  /**
   * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
   */
  com.trak.grpc.gateway.v1.ChartMessage getChart();
  /**
   * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
   */
  com.trak.grpc.gateway.v1.ChartMessageOrBuilder getChartOrBuilder();
}
