// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

/**
 * <pre>
 * Pricing statistics for a product.
 * </pre>
 *
 * Protobuf type {@code trak.grpc.gateway.v1.ProductStatsResponse}
 */
public  final class ProductStatsResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trak.grpc.gateway.v1.ProductStatsResponse)
    ProductStatsResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductStatsResponse.newBuilder() to construct.
  private ProductStatsResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductStatsResponse() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductStatsResponse();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductStatsResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            minPrice_ = input.readUInt32();
            break;
          }
          case 16: {

            maxPrice_ = input.readUInt32();
            break;
          }
          case 25: {

            meanPrice_ = input.readDouble();
            break;
          }
          case 34: {
            com.trak.grpc.gateway.v1.ChartMessage.Builder subBuilder = null;
            if (chart_ != null) {
              subBuilder = chart_.toBuilder();
            }
            chart_ = input.readMessage(com.trak.grpc.gateway.v1.ChartMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(chart_);
              chart_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductStatsResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductStatsResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trak.grpc.gateway.v1.ProductStatsResponse.class, com.trak.grpc.gateway.v1.ProductStatsResponse.Builder.class);
  }

  public static final int MIN_PRICE_FIELD_NUMBER = 1;
  private int minPrice_;
  /**
   * <code>uint32 min_price = 1;</code>
   */
  public int getMinPrice() {
    return minPrice_;
  }

  public static final int MAX_PRICE_FIELD_NUMBER = 2;
  private int maxPrice_;
  /**
   * <code>uint32 max_price = 2;</code>
   */
  public int getMaxPrice() {
    return maxPrice_;
  }

  public static final int MEAN_PRICE_FIELD_NUMBER = 3;
  private double meanPrice_;
  /**
   * <code>double mean_price = 3;</code>
   */
  public double getMeanPrice() {
    return meanPrice_;
  }

  public static final int CHART_FIELD_NUMBER = 4;
  private com.trak.grpc.gateway.v1.ChartMessage chart_;
  /**
   * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
   */
  public boolean hasChart() {
    return chart_ != null;
  }
  /**
   * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
   */
  public com.trak.grpc.gateway.v1.ChartMessage getChart() {
    return chart_ == null ? com.trak.grpc.gateway.v1.ChartMessage.getDefaultInstance() : chart_;
  }
  /**
   * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
   */
  public com.trak.grpc.gateway.v1.ChartMessageOrBuilder getChartOrBuilder() {
    return getChart();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (minPrice_ != 0) {
      output.writeUInt32(1, minPrice_);
    }
    if (maxPrice_ != 0) {
      output.writeUInt32(2, maxPrice_);
    }
    if (meanPrice_ != 0D) {
      output.writeDouble(3, meanPrice_);
    }
    if (chart_ != null) {
      output.writeMessage(4, getChart());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (minPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, minPrice_);
    }
    if (maxPrice_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(2, maxPrice_);
    }
    if (meanPrice_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, meanPrice_);
    }
    if (chart_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getChart());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trak.grpc.gateway.v1.ProductStatsResponse)) {
      return super.equals(obj);
    }
    com.trak.grpc.gateway.v1.ProductStatsResponse other = (com.trak.grpc.gateway.v1.ProductStatsResponse) obj;

    if (getMinPrice()
        != other.getMinPrice()) return false;
    if (getMaxPrice()
        != other.getMaxPrice()) return false;
    if (java.lang.Double.doubleToLongBits(getMeanPrice())
        != java.lang.Double.doubleToLongBits(
            other.getMeanPrice())) return false;
    if (hasChart() != other.hasChart()) return false;
    if (hasChart()) {
      if (!getChart()
          .equals(other.getChart())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIN_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getMinPrice();
    hash = (37 * hash) + MAX_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getMaxPrice();
    hash = (37 * hash) + MEAN_PRICE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMeanPrice()));
    if (hasChart()) {
      hash = (37 * hash) + CHART_FIELD_NUMBER;
      hash = (53 * hash) + getChart().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.ProductStatsResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trak.grpc.gateway.v1.ProductStatsResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Pricing statistics for a product.
   * </pre>
   *
   * Protobuf type {@code trak.grpc.gateway.v1.ProductStatsResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trak.grpc.gateway.v1.ProductStatsResponse)
      com.trak.grpc.gateway.v1.ProductStatsResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductStatsResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductStatsResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trak.grpc.gateway.v1.ProductStatsResponse.class, com.trak.grpc.gateway.v1.ProductStatsResponse.Builder.class);
    }

    // Construct using com.trak.grpc.gateway.v1.ProductStatsResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      minPrice_ = 0;

      maxPrice_ = 0;

      meanPrice_ = 0D;

      if (chartBuilder_ == null) {
        chart_ = null;
      } else {
        chart_ = null;
        chartBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductStatsResponse_descriptor;
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.ProductStatsResponse getDefaultInstanceForType() {
      return com.trak.grpc.gateway.v1.ProductStatsResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.ProductStatsResponse build() {
      com.trak.grpc.gateway.v1.ProductStatsResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.ProductStatsResponse buildPartial() {
      com.trak.grpc.gateway.v1.ProductStatsResponse result = new com.trak.grpc.gateway.v1.ProductStatsResponse(this);
      result.minPrice_ = minPrice_;
      result.maxPrice_ = maxPrice_;
      result.meanPrice_ = meanPrice_;
      if (chartBuilder_ == null) {
        result.chart_ = chart_;
      } else {
        result.chart_ = chartBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trak.grpc.gateway.v1.ProductStatsResponse) {
        return mergeFrom((com.trak.grpc.gateway.v1.ProductStatsResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trak.grpc.gateway.v1.ProductStatsResponse other) {
      if (other == com.trak.grpc.gateway.v1.ProductStatsResponse.getDefaultInstance()) return this;
      if (other.getMinPrice() != 0) {
        setMinPrice(other.getMinPrice());
      }
      if (other.getMaxPrice() != 0) {
        setMaxPrice(other.getMaxPrice());
      }
      if (other.getMeanPrice() != 0D) {
        setMeanPrice(other.getMeanPrice());
      }
      if (other.hasChart()) {
        mergeChart(other.getChart());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.trak.grpc.gateway.v1.ProductStatsResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.trak.grpc.gateway.v1.ProductStatsResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int minPrice_ ;
    /**
     * <code>uint32 min_price = 1;</code>
     */
    public int getMinPrice() {
      return minPrice_;
    }
    /**
     * <code>uint32 min_price = 1;</code>
     */
    public Builder setMinPrice(int value) {
      
      minPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 min_price = 1;</code>
     */
    public Builder clearMinPrice() {
      
      minPrice_ = 0;
      onChanged();
      return this;
    }

    private int maxPrice_ ;
    /**
     * <code>uint32 max_price = 2;</code>
     */
    public int getMaxPrice() {
      return maxPrice_;
    }
    /**
     * <code>uint32 max_price = 2;</code>
     */
    public Builder setMaxPrice(int value) {
      
      maxPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 max_price = 2;</code>
     */
    public Builder clearMaxPrice() {
      
      maxPrice_ = 0;
      onChanged();
      return this;
    }

    private double meanPrice_ ;
    /**
     * <code>double mean_price = 3;</code>
     */
    public double getMeanPrice() {
      return meanPrice_;
    }
    /**
     * <code>double mean_price = 3;</code>
     */
    public Builder setMeanPrice(double value) {
      
      meanPrice_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double mean_price = 3;</code>
     */
    public Builder clearMeanPrice() {
      
      meanPrice_ = 0D;
      onChanged();
      return this;
    }

    private com.trak.grpc.gateway.v1.ChartMessage chart_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.trak.grpc.gateway.v1.ChartMessage, com.trak.grpc.gateway.v1.ChartMessage.Builder, com.trak.grpc.gateway.v1.ChartMessageOrBuilder> chartBuilder_;
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public boolean hasChart() {
      return chartBuilder_ != null || chart_ != null;
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public com.trak.grpc.gateway.v1.ChartMessage getChart() {
      if (chartBuilder_ == null) {
        return chart_ == null ? com.trak.grpc.gateway.v1.ChartMessage.getDefaultInstance() : chart_;
      } else {
        return chartBuilder_.getMessage();
      }
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public Builder setChart(com.trak.grpc.gateway.v1.ChartMessage value) {
      if (chartBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        chart_ = value;
        onChanged();
      } else {
        chartBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public Builder setChart(
        com.trak.grpc.gateway.v1.ChartMessage.Builder builderForValue) {
      if (chartBuilder_ == null) {
        chart_ = builderForValue.build();
        onChanged();
      } else {
        chartBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public Builder mergeChart(com.trak.grpc.gateway.v1.ChartMessage value) {
      if (chartBuilder_ == null) {
        if (chart_ != null) {
          chart_ =
            com.trak.grpc.gateway.v1.ChartMessage.newBuilder(chart_).mergeFrom(value).buildPartial();
        } else {
          chart_ = value;
        }
        onChanged();
      } else {
        chartBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public Builder clearChart() {
      if (chartBuilder_ == null) {
        chart_ = null;
        onChanged();
      } else {
        chart_ = null;
        chartBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public com.trak.grpc.gateway.v1.ChartMessage.Builder getChartBuilder() {
      
      onChanged();
      return getChartFieldBuilder().getBuilder();
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    public com.trak.grpc.gateway.v1.ChartMessageOrBuilder getChartOrBuilder() {
      if (chartBuilder_ != null) {
        return chartBuilder_.getMessageOrBuilder();
      } else {
        return chart_ == null ?
            com.trak.grpc.gateway.v1.ChartMessage.getDefaultInstance() : chart_;
      }
    }
    /**
     * <code>.trak.grpc.gateway.v1.ChartMessage chart = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.trak.grpc.gateway.v1.ChartMessage, com.trak.grpc.gateway.v1.ChartMessage.Builder, com.trak.grpc.gateway.v1.ChartMessageOrBuilder> 
        getChartFieldBuilder() {
      if (chartBuilder_ == null) {
        chartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.trak.grpc.gateway.v1.ChartMessage, com.trak.grpc.gateway.v1.ChartMessage.Builder, com.trak.grpc.gateway.v1.ChartMessageOrBuilder>(
                getChart(),
                getParentForChildren(),
                isClean());
        chart_ = null;
      }
      return chartBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trak.grpc.gateway.v1.ProductStatsResponse)
  }

  // @@protoc_insertion_point(class_scope:trak.grpc.gateway.v1.ProductStatsResponse)
  private static final com.trak.grpc.gateway.v1.ProductStatsResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trak.grpc.gateway.v1.ProductStatsResponse();
  }

  public static com.trak.grpc.gateway.v1.ProductStatsResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductStatsResponse>
      PARSER = new com.google.protobuf.AbstractParser<ProductStatsResponse>() {
    @java.lang.Override
    public ProductStatsResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductStatsResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductStatsResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductStatsResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trak.grpc.gateway.v1.ProductStatsResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

