// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

/**
 * <pre>
 * Message describing a Product.
 * </pre>
 *
 * Protobuf type {@code trak.grpc.gateway.v1.ProductMessage}
 */
public  final class ProductMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:trak.grpc.gateway.v1.ProductMessage)
    ProductMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ProductMessage.newBuilder() to construct.
  private ProductMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ProductMessage() {
    name_ = "";
    productUrl_ = "";
    price_ = "";
    imageUrl_ = "";
    categories_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ProductMessage();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ProductMessage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            productUrl_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            price_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            imageUrl_ = s;
            break;
          }
          case 40: {

            id_ = input.readUInt32();
            break;
          }
          case 50: {
            com.trak.grpc.gateway.v1.BrandMessage.Builder subBuilder = null;
            if (brand_ != null) {
              subBuilder = brand_.toBuilder();
            }
            brand_ = input.readMessage(com.trak.grpc.gateway.v1.BrandMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(brand_);
              brand_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              categories_ = new java.util.ArrayList<com.trak.grpc.gateway.v1.CategoryMessage>();
              mutable_bitField0_ |= 0x00000001;
            }
            categories_.add(
                input.readMessage(com.trak.grpc.gateway.v1.CategoryMessage.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        categories_ = java.util.Collections.unmodifiableList(categories_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.trak.grpc.gateway.v1.ProductMessage.class, com.trak.grpc.gateway.v1.ProductMessage.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 1;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRODUCT_URL_FIELD_NUMBER = 2;
  private volatile java.lang.Object productUrl_;
  /**
   * <code>string product_url = 2;</code>
   */
  public java.lang.String getProductUrl() {
    java.lang.Object ref = productUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      productUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string product_url = 2;</code>
   */
  public com.google.protobuf.ByteString
      getProductUrlBytes() {
    java.lang.Object ref = productUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      productUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PRICE_FIELD_NUMBER = 3;
  private volatile java.lang.Object price_;
  /**
   * <code>string price = 3;</code>
   */
  public java.lang.String getPrice() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      price_ = s;
      return s;
    }
  }
  /**
   * <code>string price = 3;</code>
   */
  public com.google.protobuf.ByteString
      getPriceBytes() {
    java.lang.Object ref = price_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      price_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IMAGE_URL_FIELD_NUMBER = 4;
  private volatile java.lang.Object imageUrl_;
  /**
   * <code>string image_url = 4;</code>
   */
  public java.lang.String getImageUrl() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imageUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string image_url = 4;</code>
   */
  public com.google.protobuf.ByteString
      getImageUrlBytes() {
    java.lang.Object ref = imageUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imageUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ID_FIELD_NUMBER = 5;
  private int id_;
  /**
   * <code>uint32 id = 5;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int BRAND_FIELD_NUMBER = 6;
  private com.trak.grpc.gateway.v1.BrandMessage brand_;
  /**
   * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
   */
  public boolean hasBrand() {
    return brand_ != null;
  }
  /**
   * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
   */
  public com.trak.grpc.gateway.v1.BrandMessage getBrand() {
    return brand_ == null ? com.trak.grpc.gateway.v1.BrandMessage.getDefaultInstance() : brand_;
  }
  /**
   * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
   */
  public com.trak.grpc.gateway.v1.BrandMessageOrBuilder getBrandOrBuilder() {
    return getBrand();
  }

  public static final int CATEGORIES_FIELD_NUMBER = 7;
  private java.util.List<com.trak.grpc.gateway.v1.CategoryMessage> categories_;
  /**
   * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
   */
  public java.util.List<com.trak.grpc.gateway.v1.CategoryMessage> getCategoriesList() {
    return categories_;
  }
  /**
   * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
   */
  public java.util.List<? extends com.trak.grpc.gateway.v1.CategoryMessageOrBuilder> 
      getCategoriesOrBuilderList() {
    return categories_;
  }
  /**
   * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
   */
  public int getCategoriesCount() {
    return categories_.size();
  }
  /**
   * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
   */
  public com.trak.grpc.gateway.v1.CategoryMessage getCategories(int index) {
    return categories_.get(index);
  }
  /**
   * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
   */
  public com.trak.grpc.gateway.v1.CategoryMessageOrBuilder getCategoriesOrBuilder(
      int index) {
    return categories_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getProductUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, productUrl_);
    }
    if (!getPriceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, price_);
    }
    if (!getImageUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageUrl_);
    }
    if (id_ != 0) {
      output.writeUInt32(5, id_);
    }
    if (brand_ != null) {
      output.writeMessage(6, getBrand());
    }
    for (int i = 0; i < categories_.size(); i++) {
      output.writeMessage(7, categories_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getProductUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, productUrl_);
    }
    if (!getPriceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, price_);
    }
    if (!getImageUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageUrl_);
    }
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(5, id_);
    }
    if (brand_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getBrand());
    }
    for (int i = 0; i < categories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, categories_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.trak.grpc.gateway.v1.ProductMessage)) {
      return super.equals(obj);
    }
    com.trak.grpc.gateway.v1.ProductMessage other = (com.trak.grpc.gateway.v1.ProductMessage) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getProductUrl()
        .equals(other.getProductUrl())) return false;
    if (!getPrice()
        .equals(other.getPrice())) return false;
    if (!getImageUrl()
        .equals(other.getImageUrl())) return false;
    if (getId()
        != other.getId()) return false;
    if (hasBrand() != other.hasBrand()) return false;
    if (hasBrand()) {
      if (!getBrand()
          .equals(other.getBrand())) return false;
    }
    if (!getCategoriesList()
        .equals(other.getCategoriesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + PRODUCT_URL_FIELD_NUMBER;
    hash = (53 * hash) + getProductUrl().hashCode();
    hash = (37 * hash) + PRICE_FIELD_NUMBER;
    hash = (53 * hash) + getPrice().hashCode();
    hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
    hash = (53 * hash) + getImageUrl().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    if (hasBrand()) {
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
    }
    if (getCategoriesCount() > 0) {
      hash = (37 * hash) + CATEGORIES_FIELD_NUMBER;
      hash = (53 * hash) + getCategoriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.trak.grpc.gateway.v1.ProductMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.trak.grpc.gateway.v1.ProductMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Message describing a Product.
   * </pre>
   *
   * Protobuf type {@code trak.grpc.gateway.v1.ProductMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:trak.grpc.gateway.v1.ProductMessage)
      com.trak.grpc.gateway.v1.ProductMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.trak.grpc.gateway.v1.ProductMessage.class, com.trak.grpc.gateway.v1.ProductMessage.Builder.class);
    }

    // Construct using com.trak.grpc.gateway.v1.ProductMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCategoriesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      productUrl_ = "";

      price_ = "";

      imageUrl_ = "";

      id_ = 0;

      if (brandBuilder_ == null) {
        brand_ = null;
      } else {
        brand_ = null;
        brandBuilder_ = null;
      }
      if (categoriesBuilder_ == null) {
        categories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        categoriesBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.trak.grpc.gateway.v1.GatewayApiProto.internal_static_trak_grpc_gateway_v1_ProductMessage_descriptor;
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.ProductMessage getDefaultInstanceForType() {
      return com.trak.grpc.gateway.v1.ProductMessage.getDefaultInstance();
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.ProductMessage build() {
      com.trak.grpc.gateway.v1.ProductMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.trak.grpc.gateway.v1.ProductMessage buildPartial() {
      com.trak.grpc.gateway.v1.ProductMessage result = new com.trak.grpc.gateway.v1.ProductMessage(this);
      int from_bitField0_ = bitField0_;
      result.name_ = name_;
      result.productUrl_ = productUrl_;
      result.price_ = price_;
      result.imageUrl_ = imageUrl_;
      result.id_ = id_;
      if (brandBuilder_ == null) {
        result.brand_ = brand_;
      } else {
        result.brand_ = brandBuilder_.build();
      }
      if (categoriesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          categories_ = java.util.Collections.unmodifiableList(categories_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.categories_ = categories_;
      } else {
        result.categories_ = categoriesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.trak.grpc.gateway.v1.ProductMessage) {
        return mergeFrom((com.trak.grpc.gateway.v1.ProductMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.trak.grpc.gateway.v1.ProductMessage other) {
      if (other == com.trak.grpc.gateway.v1.ProductMessage.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getProductUrl().isEmpty()) {
        productUrl_ = other.productUrl_;
        onChanged();
      }
      if (!other.getPrice().isEmpty()) {
        price_ = other.price_;
        onChanged();
      }
      if (!other.getImageUrl().isEmpty()) {
        imageUrl_ = other.imageUrl_;
        onChanged();
      }
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (other.hasBrand()) {
        mergeBrand(other.getBrand());
      }
      if (categoriesBuilder_ == null) {
        if (!other.categories_.isEmpty()) {
          if (categories_.isEmpty()) {
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCategoriesIsMutable();
            categories_.addAll(other.categories_);
          }
          onChanged();
        }
      } else {
        if (!other.categories_.isEmpty()) {
          if (categoriesBuilder_.isEmpty()) {
            categoriesBuilder_.dispose();
            categoriesBuilder_ = null;
            categories_ = other.categories_;
            bitField0_ = (bitField0_ & ~0x00000001);
            categoriesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCategoriesFieldBuilder() : null;
          } else {
            categoriesBuilder_.addAllMessages(other.categories_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.trak.grpc.gateway.v1.ProductMessage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.trak.grpc.gateway.v1.ProductMessage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object productUrl_ = "";
    /**
     * <code>string product_url = 2;</code>
     */
    public java.lang.String getProductUrl() {
      java.lang.Object ref = productUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        productUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string product_url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getProductUrlBytes() {
      java.lang.Object ref = productUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        productUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string product_url = 2;</code>
     */
    public Builder setProductUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      productUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string product_url = 2;</code>
     */
    public Builder clearProductUrl() {
      
      productUrl_ = getDefaultInstance().getProductUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string product_url = 2;</code>
     */
    public Builder setProductUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      productUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object price_ = "";
    /**
     * <code>string price = 3;</code>
     */
    public java.lang.String getPrice() {
      java.lang.Object ref = price_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        price_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string price = 3;</code>
     */
    public com.google.protobuf.ByteString
        getPriceBytes() {
      java.lang.Object ref = price_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        price_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string price = 3;</code>
     */
    public Builder setPrice(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      price_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string price = 3;</code>
     */
    public Builder clearPrice() {
      
      price_ = getDefaultInstance().getPrice();
      onChanged();
      return this;
    }
    /**
     * <code>string price = 3;</code>
     */
    public Builder setPriceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      price_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object imageUrl_ = "";
    /**
     * <code>string image_url = 4;</code>
     */
    public java.lang.String getImageUrl() {
      java.lang.Object ref = imageUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      java.lang.Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public Builder setImageUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imageUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public Builder clearImageUrl() {
      
      imageUrl_ = getDefaultInstance().getImageUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string image_url = 4;</code>
     */
    public Builder setImageUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imageUrl_ = value;
      onChanged();
      return this;
    }

    private int id_ ;
    /**
     * <code>uint32 id = 5;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 5;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 5;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private com.trak.grpc.gateway.v1.BrandMessage brand_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.trak.grpc.gateway.v1.BrandMessage, com.trak.grpc.gateway.v1.BrandMessage.Builder, com.trak.grpc.gateway.v1.BrandMessageOrBuilder> brandBuilder_;
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public boolean hasBrand() {
      return brandBuilder_ != null || brand_ != null;
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public com.trak.grpc.gateway.v1.BrandMessage getBrand() {
      if (brandBuilder_ == null) {
        return brand_ == null ? com.trak.grpc.gateway.v1.BrandMessage.getDefaultInstance() : brand_;
      } else {
        return brandBuilder_.getMessage();
      }
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public Builder setBrand(com.trak.grpc.gateway.v1.BrandMessage value) {
      if (brandBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        brand_ = value;
        onChanged();
      } else {
        brandBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public Builder setBrand(
        com.trak.grpc.gateway.v1.BrandMessage.Builder builderForValue) {
      if (brandBuilder_ == null) {
        brand_ = builderForValue.build();
        onChanged();
      } else {
        brandBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public Builder mergeBrand(com.trak.grpc.gateway.v1.BrandMessage value) {
      if (brandBuilder_ == null) {
        if (brand_ != null) {
          brand_ =
            com.trak.grpc.gateway.v1.BrandMessage.newBuilder(brand_).mergeFrom(value).buildPartial();
        } else {
          brand_ = value;
        }
        onChanged();
      } else {
        brandBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public Builder clearBrand() {
      if (brandBuilder_ == null) {
        brand_ = null;
        onChanged();
      } else {
        brand_ = null;
        brandBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public com.trak.grpc.gateway.v1.BrandMessage.Builder getBrandBuilder() {
      
      onChanged();
      return getBrandFieldBuilder().getBuilder();
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    public com.trak.grpc.gateway.v1.BrandMessageOrBuilder getBrandOrBuilder() {
      if (brandBuilder_ != null) {
        return brandBuilder_.getMessageOrBuilder();
      } else {
        return brand_ == null ?
            com.trak.grpc.gateway.v1.BrandMessage.getDefaultInstance() : brand_;
      }
    }
    /**
     * <code>.trak.grpc.gateway.v1.BrandMessage brand = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.trak.grpc.gateway.v1.BrandMessage, com.trak.grpc.gateway.v1.BrandMessage.Builder, com.trak.grpc.gateway.v1.BrandMessageOrBuilder> 
        getBrandFieldBuilder() {
      if (brandBuilder_ == null) {
        brandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.trak.grpc.gateway.v1.BrandMessage, com.trak.grpc.gateway.v1.BrandMessage.Builder, com.trak.grpc.gateway.v1.BrandMessageOrBuilder>(
                getBrand(),
                getParentForChildren(),
                isClean());
        brand_ = null;
      }
      return brandBuilder_;
    }

    private java.util.List<com.trak.grpc.gateway.v1.CategoryMessage> categories_ =
      java.util.Collections.emptyList();
    private void ensureCategoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        categories_ = new java.util.ArrayList<com.trak.grpc.gateway.v1.CategoryMessage>(categories_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.trak.grpc.gateway.v1.CategoryMessage, com.trak.grpc.gateway.v1.CategoryMessage.Builder, com.trak.grpc.gateway.v1.CategoryMessageOrBuilder> categoriesBuilder_;

    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public java.util.List<com.trak.grpc.gateway.v1.CategoryMessage> getCategoriesList() {
      if (categoriesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(categories_);
      } else {
        return categoriesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public int getCategoriesCount() {
      if (categoriesBuilder_ == null) {
        return categories_.size();
      } else {
        return categoriesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public com.trak.grpc.gateway.v1.CategoryMessage getCategories(int index) {
      if (categoriesBuilder_ == null) {
        return categories_.get(index);
      } else {
        return categoriesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder setCategories(
        int index, com.trak.grpc.gateway.v1.CategoryMessage value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.set(index, value);
        onChanged();
      } else {
        categoriesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder setCategories(
        int index, com.trak.grpc.gateway.v1.CategoryMessage.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.set(index, builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder addCategories(com.trak.grpc.gateway.v1.CategoryMessage value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.add(value);
        onChanged();
      } else {
        categoriesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder addCategories(
        int index, com.trak.grpc.gateway.v1.CategoryMessage value) {
      if (categoriesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCategoriesIsMutable();
        categories_.add(index, value);
        onChanged();
      } else {
        categoriesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder addCategories(
        com.trak.grpc.gateway.v1.CategoryMessage.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.add(builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder addCategories(
        int index, com.trak.grpc.gateway.v1.CategoryMessage.Builder builderForValue) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.add(index, builderForValue.build());
        onChanged();
      } else {
        categoriesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder addAllCategories(
        java.lang.Iterable<? extends com.trak.grpc.gateway.v1.CategoryMessage> values) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, categories_);
        onChanged();
      } else {
        categoriesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder clearCategories() {
      if (categoriesBuilder_ == null) {
        categories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        categoriesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public Builder removeCategories(int index) {
      if (categoriesBuilder_ == null) {
        ensureCategoriesIsMutable();
        categories_.remove(index);
        onChanged();
      } else {
        categoriesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public com.trak.grpc.gateway.v1.CategoryMessage.Builder getCategoriesBuilder(
        int index) {
      return getCategoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public com.trak.grpc.gateway.v1.CategoryMessageOrBuilder getCategoriesOrBuilder(
        int index) {
      if (categoriesBuilder_ == null) {
        return categories_.get(index);  } else {
        return categoriesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public java.util.List<? extends com.trak.grpc.gateway.v1.CategoryMessageOrBuilder> 
         getCategoriesOrBuilderList() {
      if (categoriesBuilder_ != null) {
        return categoriesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(categories_);
      }
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public com.trak.grpc.gateway.v1.CategoryMessage.Builder addCategoriesBuilder() {
      return getCategoriesFieldBuilder().addBuilder(
          com.trak.grpc.gateway.v1.CategoryMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public com.trak.grpc.gateway.v1.CategoryMessage.Builder addCategoriesBuilder(
        int index) {
      return getCategoriesFieldBuilder().addBuilder(
          index, com.trak.grpc.gateway.v1.CategoryMessage.getDefaultInstance());
    }
    /**
     * <code>repeated .trak.grpc.gateway.v1.CategoryMessage categories = 7;</code>
     */
    public java.util.List<com.trak.grpc.gateway.v1.CategoryMessage.Builder> 
         getCategoriesBuilderList() {
      return getCategoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.trak.grpc.gateway.v1.CategoryMessage, com.trak.grpc.gateway.v1.CategoryMessage.Builder, com.trak.grpc.gateway.v1.CategoryMessageOrBuilder> 
        getCategoriesFieldBuilder() {
      if (categoriesBuilder_ == null) {
        categoriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.trak.grpc.gateway.v1.CategoryMessage, com.trak.grpc.gateway.v1.CategoryMessage.Builder, com.trak.grpc.gateway.v1.CategoryMessageOrBuilder>(
                categories_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        categories_ = null;
      }
      return categoriesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:trak.grpc.gateway.v1.ProductMessage)
  }

  // @@protoc_insertion_point(class_scope:trak.grpc.gateway.v1.ProductMessage)
  private static final com.trak.grpc.gateway.v1.ProductMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.trak.grpc.gateway.v1.ProductMessage();
  }

  public static com.trak.grpc.gateway.v1.ProductMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ProductMessage>
      PARSER = new com.google.protobuf.AbstractParser<ProductMessage>() {
    @java.lang.Override
    public ProductMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ProductMessage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ProductMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ProductMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.trak.grpc.gateway.v1.ProductMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

