// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.trak.grpc.gateway.v1.ProductMessage product = 1;</code>
   */
  boolean hasProduct();
  /**
   * <code>.trak.grpc.gateway.v1.ProductMessage product = 1;</code>
   */
  com.trak.grpc.gateway.v1.ProductMessage getProduct();
  /**
   * <code>.trak.grpc.gateway.v1.ProductMessage product = 1;</code>
   */
  com.trak.grpc.gateway.v1.ProductMessageOrBuilder getProductOrBuilder();

  /**
   * <code>.trak.grpc.gateway.v1.ProductStatsResponse stats = 2;</code>
   */
  boolean hasStats();
  /**
   * <code>.trak.grpc.gateway.v1.ProductStatsResponse stats = 2;</code>
   */
  com.trak.grpc.gateway.v1.ProductStatsResponse getStats();
  /**
   * <code>.trak.grpc.gateway.v1.ProductStatsResponse stats = 2;</code>
   */
  com.trak.grpc.gateway.v1.ProductStatsResponseOrBuilder getStatsOrBuilder();
}
