// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/gateway/gateway_api.proto

package com.trak.grpc.gateway.v1;

public interface PromotionMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:trak.grpc.gateway.v1.PromotionMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 promotion_id = 3;</code>
   */
  int getPromotionId();

  /**
   * <code>uint32 start = 4;</code>
   */
  int getStart();

  /**
   * <code>uint32 end = 5;</code>
   */
  int getEnd();
}
